const express = require("express")
const viewsController = require("../controllers/viewsController.js")
const authController = require("../controllers/authController.js")
const ViewsRouter = express.Router()

ViewsRouter.route("/").get(authController.isLoggedIn, viewsController.getHomePage)
ViewsRouter.route("/test").get(viewsController.getTestPage)
ViewsRouter.route("/cart").get(viewsController.getCartPage)
ViewsRouter.route("/get-orderpage").get(viewsController.getOrderPage)
ViewsRouter.route("/admin-login").get(viewsController.getAdminLoginPage)
ViewsRouter.route("/signup").get(viewsController.getSignupPage)
ViewsRouter.route("/404").get(viewsController.get404Page)
ViewsRouter.route("/about-us").get(viewsController.getAboutUsPage)
ViewsRouter.route("/basic-settings").get(authController.protect, viewsController.getBasicSettingsPage)
ViewsRouter.route("/site-settings").get(authController.protect, viewsController.getSiteSettingsPage)
ViewsRouter.route("/bookings").get(authController.protect, viewsController.getBookingPage)
ViewsRouter.route("/coming-soon").get(viewsController.getComingSoonPage)
ViewsRouter.route("/contact").get(viewsController.getContactPage)
ViewsRouter.route("/dashboard").get(authController.protect, authController.protect, viewsController.getDashboardPage)
ViewsRouter.route("/faqs").get(viewsController.getFAQsPage)
ViewsRouter.route("/guide-detail").get(viewsController.getGuideDetailPage)
ViewsRouter.route("/hire-guide").get(viewsController.getHireGuidePage)
ViewsRouter.route("/invoice").get(authController.protect, viewsController.getInvoicePage)
ViewsRouter.route("/messages").get(authController.protect, viewsController.getMessagesPage)
ViewsRouter.route("/replies/:id").get(authController.protect, viewsController.getRepliesPage)
ViewsRouter.route("/my-profile").get(authController.protect, viewsController.getMyProfilePage)
ViewsRouter.route("/pricing").get(viewsController.getPricingPage)
ViewsRouter.route("/success").get(viewsController.getSuccessPage)
ViewsRouter.route("/forgot-password").get(viewsController.getForgotPasswordPage)
ViewsRouter.route("/reset-password").get(viewsController.getResetPasswordPage)

ViewsRouter.route("/add-destination").get(authController.protect, viewsController.getAddDestinationPage)
ViewsRouter.route("/add-hotel").get(authController.protect, viewsController.getAddHotelPage)
ViewsRouter.route("/add-restaurant").get(authController.protect, viewsController.getAddRestaurantPage)
ViewsRouter.route("/add-tour").get(authController.protect, viewsController.getAddTourPage)


ViewsRouter.route("/manage-destinations").get(authController.protect, viewsController.getManageDestinationsPage)
ViewsRouter.route("/manage-tours").get(authController.protect, viewsController.getManageToursPage)
ViewsRouter.route("/manage-restaurants").get(authController.protect, viewsController.getManageRestaurantsPage)
ViewsRouter.route("/manage-hotels").get(authController.protect, viewsController.getManageHotelsPage)

ViewsRouter.route("/dest-edit/:id").get(authController.protect, viewsController.getEditDestinationPage)
ViewsRouter.route("/hotel-edit/:id").get(authController.protect, viewsController.getEditHotelPage)
ViewsRouter.route("/rest-edit/:id").get(authController.protect, viewsController.getEditRestaurantPage)
ViewsRouter.route("/tour-edit/:id").get(authController.protect, viewsController.getEditTourPage)

ViewsRouter.route("/destination-detail").get(viewsController.getDestinationDetailPage)
ViewsRouter.route("/destination-grid-sidebar").get(viewsController.getDestinationGridSidebarPage)
ViewsRouter.route("/destination-grid").get(viewsController.getDestinationGridPage)
ViewsRouter.route("/destination-list-sidebar").get(viewsController.getDestinationListSidebarPage)
ViewsRouter.route("/destination-list").get(viewsController.getDestinationListPage)

ViewsRouter.route("/hotel-detail").get(viewsController.getHotelDetailPage)
ViewsRouter.route("/hotel-grid-sidebar").get(viewsController.getHotelGridSidebarPage)
ViewsRouter.route("/hotel-grid").get(viewsController.getHotelGridPage)
ViewsRouter.route("/hotel-list-sidebar").get(viewsController.getHotelListSidebarPage)
ViewsRouter.route("/hotel-list").get(viewsController.getHotelListPage)

ViewsRouter.route("/restaurant-detail").get(viewsController.getRestaurantDetailPage)
ViewsRouter.route("/restaurant-grid-sidebar").get(viewsController.getRestaurantGridSidebarPage)
ViewsRouter.route("/restaurant-grid").get(viewsController.getRestaurantGridPage)
ViewsRouter.route("/restaurant-list-sidebar").get(viewsController.getRestaurantListSidebarPage)
ViewsRouter.route("/restaurant-list").get(viewsController.getRestaurantListPage)

ViewsRouter.route("/tour/:slug").get(viewsController.getSingleTourDetailPage)
ViewsRouter.route("/tours-grid-sidebar").get(viewsController.getAllToursGridSidebarPage)
ViewsRouter.route("/tours-grid").get(viewsController.getAllToursGridPage)
ViewsRouter.route("/tours-list-sidebar").get(viewsController.getAllToursListSidebarPage)
ViewsRouter.route("/tours-list").get(viewsController.getAllToursListPage)


// ViewsRouter.route("/forgotpassword").get(viewsController.getForgotPasswordPage)
// ViewsRouter.route("/my-dashboard").get(authController.protect, authController.isLoggedIn, viewsController.getDashboardPage)
// ViewsRouter.route("/bookings-panel").get(authController.protect, authController.isLoggedIn, viewsController.getBookingsPanel)
// ViewsRouter.route("/reviews-panel").get(authController.protect, authController.isLoggedIn, viewsController.getReviewsPanel)
// ViewsRouter.route("/users-panel").get(authController.protect, authController.isLoggedIn, viewsController.getUsersPanel)
// ViewsRouter.route("/security").get(authController.protect, authController.isLoggedIn, viewsController.getSecuritypage)


module.exports = ViewsRouter